#!/bin/bash

# 1. Install Vim
echo "Installing Vim..."
sudo apt update
sudo apt install -y vim

# 2. Install vim-plug
echo "Installing vim-plug..."
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# 3. Remove existing .vim directory if exists
if [ -d "~/.vim" ]; then
    echo "Removing existing ~/.vim directory..."
    rm -rf ~/.vim
fi

# 4. Clone the Vim configurations repository
echo "Cloning Vim configurations..."
git clone https://github.com/luisvillegasbf23/my_vim.git ~/.vim

# 5. Create symbolic links for .vimrc from configs folder
echo "Creating symbolic link for .vimrc from configs folder..."
ln -sf ~/.vim/configs/.vimrc ~/.vimrc

# 6. Copy additional configurations
if [ -d "~/.vim/configs" ]; then
    echo "Copying additional configurations..."
    cp -r ~/.vim/configs/* ~/.vim
else
    echo "No additional configs found in ~/.vim/configs."
fi

# 7. Install plugins using vim-plug
echo "Installing Vim plugins..."
vim -E -s +PlugInstall +qall

echo "Vim configuration completed."

